# Passenger service default security properties
# security user credentials (override via env)
security.user.name=${SECURITY_USER_NAME:root}
security.user.password=${SECURITY_USER_PASSWORD:Rahul@1234}
# MySQL DB
spring.datasource.url=jdbc:mysql://localhost:3306/airline_db?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Rahul@1234}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Initialize schema/data in flight
spring.sql.init.mode=always


# Service port
spring.config.import=optional:configserver:http://localhost:8888

server.port=8081
spring.application.name=passengerservice
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Set Eureka status page URL to /passengers/all
eureka.instance.status-page-url-path=/passengers/all

# Dev: include stacktraces and messages in error responses (remove in production)
server.error.include-message=always
server.error.include-stacktrace=always
