INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (201, 'Indigo', 'Rahul Jangir');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (202, 'Spice Jet', 'Viraj Yadav');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (203, 'AirAsia', 'Priya Singh');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (204, 'Kingfisher', 'Sneha Gupta');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (205, 'Air India', 'Amit Kumar');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (206, 'Go Air', 'Neha Sharma');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (207, 'AI208', 'Rohit Verma');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (208, 'AI209', 'Anjali Mehta');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (209, 'AI210', 'Karan Patel');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (210, 'AI211', 'Simran Kaur');
INSERT INTO Bookings (id, flight_number, passenger_name) VALUES (211, 'AI212', 'Vikram Joshi');