spring.application.name=eurekaserver
server.port=8761


# eureka server settings
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.server.enableReplication=false
eureka.instance.homePageUrl=http://localhost:8761/

spring.security.user.name=${SERVICE_SECURITY_USER_NAME:root}
spring.security.user.password=${SERVICE_SECURITY_USER_PASSWORD:Rahul@1234}