# API Gateway default security properties
security.user.name=${SECURITY_USER_NAME:root}
security.user.password=${SECURITY_USER_PASSWORD:Rahul@1234}
# Ensure reactive web application type for Spring Cloud Gateway
# spring.main.web-application-type=reactive
#server.port=8080
#spring.application.name=api-gateway
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/ 

spring.application.name=apigateway
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.username=${CONFIG_SERVER_CLIENT_USERNAME:root}
spring.cloud.config.password=${CONFIG_SERVER_CLIENT_PASSWORD:Rahul@1234}
eureka.instance.status-page-url-path=/bookings/all


