spring.application.name=configurationserver
server.port=8888
#spring.profiles.active=native
spring.security.user.name=${CONFIG_SERVER_ADMIN_USERNAME:root}
# Use environment variable CONFIG_SERVER_ADMIN_PASSWORD or set as JVM property -Dconfig.server.admin.password
spring.security.user.password=${CONFIG_SERVER_ADMIN_PASSWORD:Rahul@1234}

#GIT_USERNAME
spring.cloud.config.server.git.username=${GIT_USERNAME}
#GIT_TOKEN
spring.cloud.config.server.git.password=${GIT_TOKEN}
spring.cloud.config.server.git.uri=https://github.com/TusharJangr/Flightsevice-config
# Ensure the search-paths match the application folders in that repo (adjust if needed)
spring.cloud.config.server.git.search-paths=bookingservice, flightservice, passengerservice, apigateway, eurekaserver


